config/routes.rb
PopstilRb::Application.routes.draw do
  
  controller :painel do
    get 'painel/cadastrar' => :cadastrar
    post 'painel' => 'painel#salvar'
    get 'painel/meusdados' => :show_dados
    post 'painel/definirendereco/:id' => :definir_endereco, :as => 'definirendereco'
    get 'adicionar_endereco' => :adicionar_endereco
    put 'adicionar_endereco' => :salvar_endereco
    get 'painel/editar' => :editar
    put 'painel/editar' => :update
    get 'painel' => :dashboard
  end
  
  controller :sessions do
    get 'login' => :new
    post 'login'=> :create
    delete 'logout'=> :destroy
  end
  root :to =>'sessions#new'
  

end

app/models/endereco.rb
class Endereco < ActiveRecord::Base
  belongs_to :user
  
  validates :cep, :endereco, :numero, :bairro, :cidade, :estado, presence: true
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :endereco, dependent: :destroy, :order => 'principal DESC'
  
  validates :nome, :sexo, :sobrenome, presence: true
  validates :cpf, :email, :username, presence: true, uniqueness: true
  has_secure_password
  
  accepts_nested_attributes_for :endereco, allow_destroy: true
  
  def get_endereco
    self.endereco.map! do |endereco|
      Endereco.find_or_create_by_id(endereco.id)
    end
  end
  
  def to_s
    "Id: #{id}, Nome: #{nome}, Username: #{username}"
  end    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user
  
  private 
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  protected
  def authorize
    unless User.find_by_id(session[:user_id])
      redirect_to login_url, alert: 'Eh necessario estar logado para acessar essa pagina'
    end
  end
  
  def user_logged
    if User.find_by_id(session[:user_id])
      redirect_to painel_path
    end
  end
  
  
end

app/controllers/painel_controller.rb
class PainelController < ApplicationController
  before_filter :authorize, except: [:cadastrar, :salvar]
  before_filter :user_logged, only: [:cadastrar]
  before_action :set_user, only: [:editar, :update, :show_dados, :salvar_endereco]
  
  #GET /painel/cadastrar
  def cadastrar
    @user = User.new
    @user.endereco.build
  end
  
  def dashboard
    
  end
  
  
  #POST /painel
  def salvar
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: 'Seu cadastro foi realizado com sucesso.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'cadastrar' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  #GET /painel/editar/:id
  def editar
  end
  
  #PUT /painel/editar/:id
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html {redirect_to painel_path, notice: 'Seu cadastro foi atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: 'editar' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  #GET /painel/meusdados
  def show_dados
    
  end
  
  def definir_endereco
    begin
    endereco = Endereco.find(params[:id])
    rescue ActiveRecord::RecordNotFound
    end
    if endereco
      endereco.user.endereco.update_all(:principal => '0')
      endereco.update_attributes(:principal => '1')
      redirect_to painel_meusdados_path, notice: 'Endereco principal alterado'
    else
    redirect_to painel_meusdados_path, notice: 'Endereco nao encontrado, tente novamente '    
    end  
  end
  
  def adicionar_endereco
    @endereco = Endereco.new
  end
  
  def salvar_endereco
    @endereco = Endereco.new(endereco_params)
    @endereco.user = @user
    @endereco.principal = '0'
    respond_to do |format|
      if @endereco.save
        format.html { redirect_to painel_meusdados_path, notice: 'Seu endereco foi adicionado com sucesso.' }
      else
        format.html { render action: 'adicionar_endereco' }
        format.json { render json: @endereco.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def set_user
    @user = User.find(session[:user_id])
  end
  
  def user_params
    params.require(:user).permit(:id, :nome,:sobrenome, :cpf, :sexo, :data_nascimento, :username, :email, :password, 
      :password_confirmation, endereco_attributes: [:id, :cep, :tipo, :endereco, :numero, :complemento, :bairro, :cidade, :estado])
  end
  def endereco_params 
    params.require(:endereco).permit(:id, :cep, :tipo, :endereco, :numero, :complemento, :bairro, :cidade, :estado)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :user_logged, only: [:new]
  
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to login_url, alert: "Seja bem vindo"
    else
      redirect_to login_url, alert: 'E-mail ou senha incorretos'
    end  
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_url, alert: 'Logout realizando com sucesso'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/painel_helper.rb
module PainelHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PopstilRb</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="header">
	<div class="container">
		<div class="row">
		    <div class="logo span3">
		      <a href="/index.php">
		        <%= image_tag "logo_popstil.png" %>
		      </a>
		    </div>
		    <div class="menus">
			    <div class="menu">
			    	<ul class="">
						<li>Carrinho</li>
						<li>Realizar compra</li>
						<% if session[:user_id] %>
							<li><%= link_to 'Meu Popstil', painel_path %></li>
						<% else %>
							<li><%= link_to 'Acessar', login_path %></li>
						<% end %>
					</ul>						
			    </div>
		    	<div class="menu_user">
			    	<% if session[:user_id] %>
						<p>Olá, <%= self.current_user.nome %></p>
						<%= link_to 'Logout', logout_path, method: :delete %>
					<% else %>
					<p>&nbsp;</p>		
					<% end %>
			    </div>
		    </div>
		</div>
    </div>
</div>
<%= yield %>

</body>
</html>

app/views/painel/_form.html.erb
	
			<% if @user.errors.any? %>
			    <div id="error_explanation">
			      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this cliente from being saved:</h2>
			
			      <ul>
			      <% @user.errors.full_messages.each do |msg| %>
			        <li><%= msg %></li>
			      <% end %>
			      </ul>
			    </div>
		  	<% end %>
		  	<div class="msgCadastro span5" style="float:right">
				<%= image_tag("cadastro_"+(rand(1..3).to_s)+".png")  %>
				<div class="msgCadastroTexto">
					<h2>Chegou a sua vez de ter um <p>popstil!</p></h2>	
					<h4>Tendo seu cadastro você poderá efetuar novos pedidos e ainda ser o primeiro a saber das 		
					novidades da Popstil.com!</h4>
				</div>
			</div>
			<div class="cadastro_input">
				<div class="span7">
					<%= f.text_field :nome, placeholder: 'Nome', size: '100px', style:'width:350px' %>
				</div>
			</div>
			<div class="cadastro_input">
				<div class="span7">
					<%= f.text_field :sobrenome, placeholder: 'Sobrenome', size: '100px', style:'width:350px' %>
				</div>
			</div>
			<div class="cadastro_input">
				<div class="span7">
					<%= f.text_field :cpf, placeholder: 'CPF', size: '50px' %>
				</div>
			</div>
			<div class="cadastro_input">
				<div class="span7">
					<%= f.date_field :data_nascimento, placeholder: 'Data de nascimento', size: '50px' %>
				</div>
			</div>
			<div class="cadastro_input">
				<div class="span7">
					<%= f.select :sexo, [["Masculino",'M'], ["Feminino",'F']], prompt: 'Sexo'  %>
				</div>
			</div>			
		</div>
		<div class="row">
			<div class="span12">
				<hr class="linha_divisao"/>
			</div>
			<div class="cadastro_input">
				<div class="span12">
					<%= f.text_field :username, placeholder: 'Como gostaria de ser chamado?', style:'width: 280px' %>
				</div>
			</div>
			<div class="cadastro_input">
				<div class="span3">
					<%= f.email_field :email, placeholder: 'E-mail' %>
				</div>
			</div>
			<div class="cadastro_input">
				<div class="span6">
					<%= f.label :receber_newsletter, 'Gostaria de receber e-mails com novidades, ofertas e promoções especiais da pospstil.com?'%>
				</div>
				<div class="span3">	
				  	<%= f.radio_button :receber_newsletter, '1' %><span>Sim</span>
				  	<%= f.radio_button :receber_newsletter, '0' %><span>Não</span>
				</div>
			</div>
			<div class="cadastro_input">
				<div class="span12">
					<%= f.password_field :password, placeholder: 'Senha' %>
				</div>
			</div>
			<div class="cadastro_input">
				<div class="span12">
					<%= f.password_field :password_confirmation, placeholder: 'Confirmar senha' %>
				</div>
			</div>		  		  
		</div>		

app/views/painel/_menu.html.erb
<hr class="linha_divisao"/>
		
<div class="container">
	<div class="painel_menu">
		
		<div class="span12 clearfix navbar" >
			<ul class="nav direita">
				<li class=""><%= link_to "Painel de controle", painel_path %></li>
				<li class=""><%= link_to "Meus dados", painel_meusdados_path %></li>
				<li class=""><a href="#">Seu carrinho</a></li>
			</ul>
		</div>
	</div>
</div>		
<hr class="linha_divisao"/>

app/views/painel/adicionar_endereco.html.erb
<div id="corpo_cadastro" class="container">
	<div class="row">
		|<div class="span12">
			<h3>CADASTRO DE ENDEREÇO</h3>
			<hr class="linha_divisao"/>
		</div>
		<% if @endereco.errors.any? %>
			    <div id="error_explanation">
			      <h2><%= pluralize(@endereco.errors.count, "error") %> prohibited this cliente from being saved:</h2>
			
			      <ul>
			      <% @endereco.errors.full_messages.each do |msg| %>
			        <li><%= msg %></li>
			      <% end %>
			      </ul>
			    </div>
		  	<% end %>
		<%= form_for @endereco, :url => adicionar_endereco_path, :html => {:method => 'put'} do |endereco_form|%>
			<div class="cadastro_input">
				<div class="span12">
					<%= endereco_form.text_field :cep, placeholder: 'CEP' %>
				</div>
			</div>
			<div class="cadastro_input">
				<div class="span12">
					<%= endereco_form.label :tipo_endereco, 'Identificacao do endereço'%>	
				  	<%= endereco_form.radio_button :tipo_endereco, 'Casa' %>Casa
				  	<%= endereco_form.radio_button :tipo_endereco, 'Apartamento' %>Apto
				  	<%= endereco_form.radio_button :tipo_endereco, 'Comercial' %>Comercial
				</div>
			</div>
			<div class="cadastro_input">
				<div class="span12">
					<%= endereco_form.text_field :endereco, placeholder: 'Endereço' %>
				</div>
			</div>
			<div class="cadastro_input">
				<div class="span12">
					<%= endereco_form.text_field :numero, placeholder: 'Número' %>
				</div>
			</div>
			<div class="cadastro_input">
				<div class="span12">
					<%= endereco_form.text_field :complemento, placeholder: 'Complemento' %>
				</div>
			</div>
			<div class="cadastro_input">
				<div class="span3">
					<%= endereco_form.text_field :bairro, placeholder: 'Bairro' %>
				</div>
			</div>
			<div class="cadastro_input">
				<div class="span7">
					<%= endereco_form.text_field :cidade, placeholder: 'Cidade' %>
				</div>
			</div>
			<div class="cadastro_input">
				<div class="span12">
					<%= endereco_form.text_field :estado, placeholder: 'Estado' %>
				</div>
			</div>
			<div class="span12">
				<hr class="linha_divisao">
			</div>
			<div class="cadastro_input" style="text-align: right">
				<div class="span12">
					<%= endereco_form.submit('Salvar endereco')%>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/painel/cadastrar.html.erb
<div id="corpo_cadastro" class="container">
	<h3>CADASTRO PESSOA FÍSICA</h3>
<hr class="linha_divisao"/>
<div class="row">
	<%= form_for @user, :url => painel_path do |f| %>
		<%= render 'form', :f => f %>
		<div class="row">
			<div class="span12">
				<h3>CADASTRO DE ENDEREÇO</h3>
				<hr class="linha_divisao"/>
			</div>
			<%= f.fields_for :endereco do |endereco_form|%>
				<div class="cadastro_input">
					<div class="span12">
						<%= endereco_form.text_field :cep, placeholder: 'CEP' %>
					</div>
				</div>
				<div class="cadastro_input">
					<div class="span12">
						<%= endereco_form.label :tipo_endereco, 'Identificacao do endereço', style: 'display:inline-block;margin: 10px 50px 20px 0px; '%>	
					  	<%= endereco_form.radio_button :tipo_endereco, 'Casa' %>Casa
					  	<%= endereco_form.radio_button :tipo_endereco, 'Apartamento' %>Apto
					  	<%= endereco_form.radio_button :tipo_endereco, 'Comercial' %>Comercial
					  	<%= endereco_form.radio_button :tipo_endereco, 'Outro' %>Outro
					</div>
				</div>
				<div class="cadastro_input">
					<div class="span12">
						<%= endereco_form.text_field :endereco, placeholder: 'Endereço' %>
					</div>
				</div>
				<div class="cadastro_input">
					<div class="span12">
						<%= endereco_form.text_field :numero, placeholder: 'Número' %>
					</div>
				</div>
				<div class="cadastro_input">
					<div class="span12">
						<%= endereco_form.text_field :complemento, placeholder: 'Complemento' %>
					</div>
				</div>
				<div class="cadastro_input">
					<div class="span3">
						<%= endereco_form.text_field :bairro, placeholder: 'Bairro' %>
					</div>
				</div>
				<div class="cadastro_input">
					<div class="span7">
						<%= endereco_form.text_field :cidade, placeholder: 'Cidade' %>
					</div>
				</div>
				<div class="cadastro_input">
					<div class="span12">
						<%= endereco_form.text_field :estado, placeholder: 'Estado' %>
					</div>
				</div>
			<% end %>
		</div>
		<div class="row">
			<div class="span12" style="text-align: right">
				<hr class="linha_divisao"/>
		    	<%= f.submit('Continuar') %>
		  	</div>
		</div>
	<% end %>
</div>

app/views/painel/dashboard.html.erb
<%= render partial:"menu" %>

app/views/painel/editar.html.erb
<p id="notice"><%= notice %></p>
<div id="corpo_cadastro" class="container">
	<h3>CADASTRO PESSOA FÍSICA</h3>
<hr class="linha_divisao"/>
<div class="row">
	<%= form_for @user, :url => {:id => @user.id},  :html => { :method => :put } do |f| %>
	<%= render 'form', :f => f %>
	<div class="row">
		<div class="span12" style="text-align: right">
			<hr class="linha_divisao"/>
	    	<%= f.submit('Salvar edição') %>
	  	</div>
	</div>
	<% end %>
</div>

app/views/painel/show_dados.html.erb
<%= render partial:"menu" %>
<h5><%= notice %></h5>
<div class="container">
	<div class="row">
		<div class="span12 direita">
			<%= link_to 'Editar', painel_editar_path %>
		</div>
		<div class="span12">
			<h2>Dados pessoais</h2>
		</div>		
		<div class="span8">
			Nome: <span><%= @user.nome+' '+@user.sobrenome %></span>
		</div>
		<div class="span8">
			CPF: <span><%= @user.cpf %></span>
		</div>
		<div class="span8">
			Date de nascimento: <span><%= @user.data_nascimento %></span>
		</div>
	</div>
	<div class="row">
		<div class="span12">
			<h2>Endereços cadastrados</h2>
		</div>
	</div>
	<div class="row">
		<div class="span12 direita">
			<%= link_to 'Adicionar novo endereco', adicionar_endereco_path %>
		</div>	
	</div>
	<% @user.endereco.each do |endereco| %>
		<div class="row">
			<div class="span8">
				<% if endereco.principal == '1' %>
					Endereco principal
					<br/>
				<% else %>
					<%= link_to 'Definir como endereco principal', definirendereco_path(endereco.id), :method=>:definir_endereco %>
				<% end %>
			</div>
			
			<div class="span8">
				CEP: <span><%= endereco.cep%></span>
			</div>
			<div class="span8">
				Endereco: <span><%= endereco.endereco%></span>
			</div>
			<div class="span8">
				Número: <span><%= endereco.numero%></span>
			</div>
		</div>
		<br/>
	<% end %>
</div>